---
title: "Macshop_Part1"
author: "Vanessa Chung"
date: "2020/12/26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(stringr)
library(dplyr)
library(tidyverse)
library(tidyr)
library(lubridate)
options(stringsAsFactors = F)
options(scipen=999)
```

# 載入資料
```{r}
load("/Users/Andy 1/Google 雲端硬碟 (r08323004@g.ntu.edu.tw)/0 Semesters/109-1/一234 資料科學/0_Final_Project/PTT_Macshop/1_data_scraping/collected_datasets/DS_Posts_iphone_2020-12-24_.rda")
```


```{r}
type_pattern <- regex("iphone3gs|iphone3g|iphone4s|iphone4|iphone5s|iphone5|iphone6s|iphone6|iphone7|iphone8|iphonexs|iphonexr|iphonex|iphone11pro|iphone11|iphone12pro|iphone12|iphonese2|iphonese1|iphonese", ignore_case=TRUE)
df_type <- Posts%>%
    # 處理時間
    mutate(ptime = parse_datetime(ptime, format = "%a %b %d %H:%M:%S %Y")) %>% 
    mutate(TimeUsed = as.numeric(ptime)) %>% 
    # 找出所有的型號
    mutate(type=str_replace_all(ptitle, "\\s", ""))%>%
    mutate(type=tolower(type))%>%
    mutate(type=str_extract(type, type_pattern))%>%
    drop_na()%>%
    # 拿出價格
    mutate(price_text = str_extract(pcontent, "價.{1,12}(\\d{2,5}){1,2}|價格.{1,8}(\\d{2,5}){1,2}")) %>% 
    mutate(price_text = gsub(",", "", price_text)) %>% 
    mutate(price = str_extract_all(price_text, "\\d{3,4}0")) %>%
    filter(lengths(price)<=2) %>% 
    drop_na() %>% 
    unnest(price) %>% 
    mutate(price = as.numeric(price)) %>% 
    # 處理交易狀況
    mutate(IsSell = ifelse(str_detect(ptitle, "\\[販售\\]|\\[賣|出售|販售|售") |
                           str_detect(string = pcontent, pattern = "售價"), 1, 0),
           IsBuy = ifelse(str_detect(ptitle, "\\[收購\\]|\\[買") |
                          str_detect(string = pcontent, pattern = "我想要買"), 1, 0),
           IsChange = ifelse(str_detect(ptitle, "\\[交換\\]|\\[換"), 1, 0))%>%
    mutate(IsSold = ifelse(str_detect(string = ptitle, pattern = "售出|已售出|已售|已出售"), 1, 0),
           IsBought = ifelse(str_detect(string = ptitle, pattern = "徵到|徵得|已徵得|已徵到|收到|已購買|已購入"), 1, 0)) 
```

```{r}
# Check
df_type %>% filter(type=="iphone4") %>% View
# iPhone各型號數量站所有貼文總數之比
df_pie <- df_type %>% 
    dplyr::group_by(type) %>% 
    dplyr::summarise(Type_Count = n()) %>% 
    arrange(desc(Type_Count))
```

# 繪製圓餅圖
```{r}
colnames(df_pie)
library(ggplot2)
data <- df_pie %>% 
    arrange(desc(Type_Count)) %>%
    mutate(prop = Type_Count / sum(Type_Count) *100) %>%
    mutate(ypos = cumsum(prop)- 0.5*prop )

## check usage
# https://stackoverflow.com/questions/47752037/pie-chart-with-ggplot2-with-specific-order-and-percentage-annotations

data %>% 
    mutate(type = factor(type, levels = rev(as.character(type)))) %>% #
    ggplot(aes(x = "", y = prop, fill = type), order = ypos)+
    geom_bar(stat = 'identity', width = 1, color = 'white')+
    coord_polar("y", start = 0)+
    #geom_text(aes(label = paste0(round(prop), "%")), 
    #          position = position_stack(vjust = 0.5)) +
    labs(x = NULL, y = NULL, fill = NULL, 
         title = "Types of iPhones Among Posts") +
    guides(fill = guide_legend(reverse = TRUE))
```

### tidy pie chart

如果後面雜項太多、比重太小，就自成一個piece
```{r}
data %>% 
    mutate(type = factor(type, levels = rev(as.character(type)))) %>% 
    mutate(label = ifelse(prop>5, paste0(round(prop,1),"%"), "")) %>%
    ggplot(aes(x = "", y = prop, fill = type), order = ypos)+
    geom_bar(stat = 'identity', width = 1, color = 'white')+
    coord_polar("y", start = 0)+
    geom_text(aes(label = label),
              position = position_stack(vjust = 0.5)) +
    labs(x = NULL, y = NULL, fill = NULL, 
         title = "Types of iPhones Among Posts") +
    guides(fill = guide_legend(reverse = TRUE))

```